language: php

sudo: false

dist: trusty

git:
  depth: 5

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  include:
    - dist: precise
      php: 5.3
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer install

script:
  - composer test
